export type MeshT = {
    type?: 'plane' | 'sphere' | 'waterPlane';
    animate?: 'on' | 'off';
    range?: 'enabled' | 'disabled';
    rangeStart?: number;
    rangeEnd?: number;
    uTime?: number;
    uSpeed?: number;
    uStrength?: number;
    uDensity?: number;
    uFrequency?: number;
    uAmplitude?: number;
    positionX?: number;
    positionY?: number;
    positionZ?: number;
    rotationX?: number;
    rotationY?: number;
    rotationZ?: number;
    color1?: string;
    color2?: string;
    color3?: string;
    reflection?: number;
    wireframe?: boolean;
    shader?: string;
    rotSpringOption?: any;
    posSpringOption?: any;
};
export type GradientT = MeshT & {
    control?: 'query' | 'props';
    isFigmaPlugin?: boolean;
    dampingFactor?: number;
    frameRate?: number;
    cAzimuthAngle?: number;
    cPolarAngle?: number;
    cDistance?: number;
    cameraZoom?: number;
    lightType?: '3d' | 'env';
    brightness?: number;
    envPreset?: 'city' | 'dawn' | 'lobby';
    grain?: 'on' | 'off';
    zoomOut?: boolean;
    toggleAxis?: boolean;
    hoverState?: string;
};
//# sourceMappingURL=types.d.ts.map