import * as React from 'react';
import { Vector2, Vector3, Color, ColorRepresentation } from 'three';
import { ReactThreeFiber } from '@react-three/fiber';
import { LineMaterial, LineMaterialParameters, Line2 } from 'three-stdlib';
export type LineProps = {
    points: Array<Vector3 | Vector2 | [number, number, number] | [number, number] | number>;
    vertexColors?: Array<Color | [number, number, number]>;
    lineWidth?: number;
} & Omit<LineMaterialParameters, 'vertexColors' | 'color'> & Omit<ReactThreeFiber.Object3DNode<Line2, typeof Line2>, 'args'> & Omit<ReactThreeFiber.Object3DNode<LineMaterial, [LineMaterialParameters]>, 'color' | 'vertexColors' | 'args'> & {
    color?: ColorRepresentation;
};
export declare const Line: React.ForwardRefExoticComponent<Pick<LineProps, "children" | "points" | "material" | "quaternion" | "color" | "fog" | "visible" | "dashed" | "transparent" | "type" | "name" | "key" | "id" | "copy" | "onUpdate" | "scale" | "clear" | "opacity" | "position" | "add" | "format" | "version" | "translateX" | "translateY" | "translateZ" | "rotateX" | "rotateY" | "rotateZ" | "clone" | "wireframe" | "attach" | "up" | "rotation" | "matrix" | "layers" | "dispose" | "toJSON" | "getWorldDirection" | "updateMatrixWorld" | "uuid" | "parent" | "modelViewMatrix" | "normalMatrix" | "matrixWorld" | "matrixAutoUpdate" | "matrixWorldAutoUpdate" | "matrixWorldNeedsUpdate" | "castShadow" | "receiveShadow" | "frustumCulled" | "renderOrder" | "animations" | "userData" | "customDepthMaterial" | "customDistanceMaterial" | "isObject3D" | "onBeforeRender" | "onAfterRender" | "applyMatrix4" | "applyQuaternion" | "setRotationFromAxisAngle" | "setRotationFromEuler" | "setRotationFromMatrix" | "setRotationFromQuaternion" | "rotateOnAxis" | "rotateOnWorldAxis" | "translateOnAxis" | "localToWorld" | "worldToLocal" | "lookAt" | "remove" | "removeFromParent" | "getObjectById" | "getObjectByName" | "getObjectByProperty" | "getObjectsByProperty" | "getWorldPosition" | "getWorldQuaternion" | "getWorldScale" | "raycast" | "traverse" | "traverseVisible" | "traverseAncestors" | "updateMatrix" | "updateWorldMatrix" | "addEventListener" | "hasEventListener" | "removeEventListener" | "dispatchEvent" | keyof import("@react-three/fiber/dist/declarations/src/core/events").EventHandlers | "resolution" | "geometry" | "alphaTest" | "alphaToCoverage" | "blendDst" | "blendDstAlpha" | "blendEquation" | "blendEquationAlpha" | "blending" | "blendSrc" | "blendSrcAlpha" | "clipIntersection" | "clippingPlanes" | "clipShadows" | "colorWrite" | "defines" | "depthFunc" | "depthTest" | "depthWrite" | "stencilWrite" | "stencilFunc" | "stencilRef" | "stencilWriteMask" | "stencilFuncMask" | "stencilFail" | "stencilZFail" | "stencilZPass" | "isMaterial" | "needsUpdate" | "polygonOffset" | "polygonOffsetFactor" | "polygonOffsetUnits" | "precision" | "premultipliedAlpha" | "forceSinglePass" | "dithering" | "side" | "shadowSide" | "toneMapped" | "vertexColors" | "onBeforeCompile" | "customProgramCacheKey" | "setValues" | "wireframeLinewidth" | "uniforms" | "dashScale" | "dashSize" | "dashOffset" | "gapSize" | "linewidth" | "worldUnits" | "isLine2" | "isLineSegments2" | "computeLineDistances" | "morphTargetInfluences" | "morphTargetDictionary" | "isMesh" | "updateMorphTargets" | "getVertexPosition" | "isLineMaterial" | "vertexShader" | "fragmentShader" | "lights" | "clipping" | "derivatives" | "extensions" | "defaultAttributeValues" | "index0AttributeName" | "uniformsNeedUpdate" | "glslVersion" | "isShaderMaterial" | "lineWidth"> & React.RefAttributes<Line2>>;
//# sourceMappingURL=Line.d.ts.map