import * as react_jsx_runtime from 'react/jsx-runtime';

type ShaderGradientCanvasContext = {
    envBasePath?: string;
};
type ShaderGradientCanvasProps = {
    children: React.ReactNode;
    style?: React.CSSProperties;
    pixelDensity?: number;
    fov?: number;
    pointerEvents?: 'none' | 'auto';
    className?: string;
    envBasePath?: string;
    lazyLoad?: boolean;
    threshold?: number;
    rootMargin?: string;
    preserveDrawingBuffer?: boolean;
    powerPreference?: WebGLPowerPreference;
};
declare const useShaderGradientCanvasContext: () => ShaderGradientCanvasContext;
declare function ShaderGradientCanvas({ children, style, pixelDensity, fov, pointerEvents, className, envBasePath, lazyLoad, threshold, rootMargin, preserveDrawingBuffer, powerPreference, }: ShaderGradientCanvasProps): react_jsx_runtime.JSX.Element;

type ShaderGradientType = 'plane' | 'waterPlane' | 'sphere';
interface Position {
    positionX: number;
    positionY: number;
    positionZ: number;
}
interface Rotation {
    rotationX: number;
    rotationY: number;
    rotationZ: number;
}
type typeT = 'plane' | 'sphere' | 'waterPlane';
type animateT = 'on' | 'off';
type MeshT = {
    type?: typeT;
    animate?: animateT;
    uTime?: number;
    uSpeed?: number;
    uStrength?: number;
    uDensity?: number;
    uFrequency?: number;
    uAmplitude?: number;
    range?: 'enabled' | 'disabled' | string;
    rangeStart?: number;
    rangeEnd?: number;
    loop?: 'on' | 'off';
    loopDuration?: number;
    positionX?: number;
    positionY?: number;
    positionZ?: number;
    rotationX?: number;
    rotationY?: number;
    rotationZ?: number;
    color1?: string;
    color2?: string;
    color3?: string;
    reflection?: number;
    wireframe?: boolean;
    shader?: string;
    rotSpringOption?: any;
    posSpringOption?: any;
};
type LightTypeT = '3d' | 'env';
type EnvironmentPresetT = 'city' | 'dawn' | 'lobby';
type LightsT = {
    lightType: LightTypeT;
    brightness: number;
    envPreset: EnvironmentPresetT;
};
type GradientT = MeshT & {
    control?: 'query' | 'props';
    isFigmaPlugin?: boolean;
    smoothTime?: number;
    cAzimuthAngle?: number;
    cPolarAngle?: number;
    cDistance?: number;
    cameraZoom?: number;
    lightType?: LightTypeT;
    brightness?: number;
    envPreset?: EnvironmentPresetT;
    grain?: 'on' | 'off';
    grainBlending?: number;
    zoomOut?: boolean;
    toggleAxis?: boolean;
    hoverState?: string;
    enableTransition?: boolean;
    enableCameraUpdate?: boolean;
    urlString?: string;
    onCameraUpdate?: (updates: Partial<GradientT>) => void;
};

declare function ShaderGradient(passedProps: GradientT): react_jsx_runtime.JSX.Element;

declare const presets: {
    halo: {
        title: string;
        color: string;
        props: {
            type: typeT;
            uAmplitude: number;
            uDensity: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            uFrequency: number;
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            axesHelper: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: EnvironmentPresetT;
            gizmoHelper: string;
            grain: string;
            lightType: LightTypeT;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            animate: animateT;
            wireframe: boolean;
        };
    };
    pensive: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            gizmoHelper: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uFrequency: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            wireframe: boolean;
        };
    };
    mint: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            gizmoHelper: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uFrequency: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            wireframe: boolean;
        };
    };
    interstella: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            gizmoHelper: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uFrequency: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            wireframe: boolean;
        };
    };
    nightyNight: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            gizmoHelper: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uFrequency: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            wireframe: boolean;
        };
    };
    violaOrientalis: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            uFrequency: number;
            wireframe: boolean;
        };
    };
    universe: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            uFrequency: number;
            wireframe: boolean;
        };
    };
    sunset: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            bgColor1: string;
            bgColor2: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            uFrequency: number;
            wireframe: boolean;
        };
    };
    mandarin: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            bgColor1: string;
            bgColor2: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            uFrequency: number;
            wireframe: boolean;
        };
    };
    cottonCandy: {
        title: string;
        color: string;
        props: {
            range: string;
            rangeStart: number;
            rangeEnd: number;
            frameRate: number;
            destination: string;
            format: string;
            animate: string;
            axesHelper: string;
            brightness: number;
            cAzimuthAngle: number;
            cDistance: number;
            cPolarAngle: number;
            cameraZoom: number;
            color1: string;
            color2: string;
            color3: string;
            embedMode: string;
            envPreset: string;
            grain: string;
            lightType: string;
            pixelDensity: number;
            fov: number;
            positionX: number;
            positionY: number;
            positionZ: number;
            reflection: number;
            rotationX: number;
            rotationY: number;
            rotationZ: number;
            shader: string;
            type: string;
            uAmplitude: number;
            uDensity: number;
            uSpeed: number;
            uStrength: number;
            uTime: number;
            uFrequency: number;
            wireframe: boolean;
        };
    };
};
declare const initialActivePreset = 0;
declare const presetsArray: ({
    title: string;
    color: string;
    props: {
        type: typeT;
        uAmplitude: number;
        uDensity: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        uFrequency: number;
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        axesHelper: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: EnvironmentPresetT;
        gizmoHelper: string;
        grain: string;
        lightType: LightTypeT;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        animate: animateT;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        gizmoHelper: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uFrequency: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        gizmoHelper: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uFrequency: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        gizmoHelper: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uFrequency: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        gizmoHelper: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uFrequency: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        uFrequency: number;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        uFrequency: number;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        bgColor1: string;
        bgColor2: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        uFrequency: number;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        bgColor1: string;
        bgColor2: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        uFrequency: number;
        wireframe: boolean;
    };
} | {
    title: string;
    color: string;
    props: {
        range: string;
        rangeStart: number;
        rangeEnd: number;
        frameRate: number;
        destination: string;
        format: string;
        animate: string;
        axesHelper: string;
        brightness: number;
        cAzimuthAngle: number;
        cDistance: number;
        cPolarAngle: number;
        cameraZoom: number;
        color1: string;
        color2: string;
        color3: string;
        embedMode: string;
        envPreset: string;
        grain: string;
        lightType: string;
        pixelDensity: number;
        fov: number;
        positionX: number;
        positionY: number;
        positionZ: number;
        reflection: number;
        rotationX: number;
        rotationY: number;
        rotationZ: number;
        shader: string;
        type: string;
        uAmplitude: number;
        uDensity: number;
        uSpeed: number;
        uStrength: number;
        uTime: number;
        uFrequency: number;
        wireframe: boolean;
    };
})[];

declare const propertyControls: (ControlType: any, type?: string) => {
    control: {
        type: any;
        options: string[];
        optionTitles: string[];
        displaySegmentedControl: boolean;
        defaultValue: string;
    };
    activeTab: {
        title: string;
        type: any;
        options: string[];
        hidden: (props: any) => boolean;
    };
    type: {
        type: any;
        options: string[];
        optionTitles: string[];
        displaySegmentedControl: boolean;
        hidden: (props: any) => boolean;
    };
    animate: {
        type: any;
        options: string[];
        optionTitles: string[];
        displaySegmentedControl: boolean;
        hidden: (props: any) => boolean;
    };
    uTime: {
        title: string;
        type: any;
        step: number;
        displayStepper: boolean;
        hidden: (props: any) => boolean;
    };
    uSpeed: {
        title: string;
        type: any;
        step: number;
        min: number;
        displayStepper: boolean;
        defaultValue: number;
        hidden: (props: any) => boolean;
    };
    noise: {
        type: any;
        controls: {
            uStrength: {
                type: any;
                title: string;
                step: number;
                min: number;
                displayStepper: boolean;
                defaultValue: number;
            };
            uDensity: {
                type: any;
                title: string;
                step: number;
                min: number;
                displayStepper: boolean;
                defaultValue: number;
            };
        };
        hidden: (props: any) => boolean;
    };
    uAmplitude: {
        type: any;
        title: string;
        step: number;
        min: number;
        displayStepper: boolean;
        defaultValue: number;
        hidden: (props: any) => boolean;
    };
    grain: {
        type: any;
        options: string[];
        optionTitles: string[];
        displaySegmentedControl: boolean;
        hidden: (props: any) => boolean;
    };
    lightType: {
        type: any;
        options: string[];
        optionTitles: string[];
        displaySegmentedControl: boolean;
        defaultValue: string;
        hidden: (props: any) => boolean;
    };
    envPreset: {
        type: any;
        options: string[];
        optionTitles: string[];
        displaySegmentedControl: boolean;
        hidden: (props: any) => boolean;
    };
    brightness: {
        type: any;
        step: number;
        min: number;
        max: number;
        defaultValue: number;
        hidden: (props: any) => any;
    };
    reflection: {
        type: any;
        step: number;
        min: number;
        max: number;
        defaultValue: number;
        hidden: (props: any) => any;
    };
    color1: {
        type: any;
        defaultValue: string;
        hidden: (props: any) => boolean;
    };
    color2: {
        type: any;
        defaultValue: string;
        hidden: (props: any) => boolean;
    };
    color3: {
        type: any;
        defaultValue: string;
        hidden: (props: any) => boolean;
    };
    cDistance: {
        title: string;
        type: any;
        displayStepper: boolean;
        min: number;
        max: number;
        defaultValue: number;
        hidden: (props: any) => boolean;
    };
    cameraZoom: {
        type: any;
        displayStepper: boolean;
        step: number;
        min: number;
        max: number;
        defaultValue: number;
        hidden: (props: any) => boolean;
    };
    cameraAngle: {
        type: any;
        controls: {
            cAzimuthAngle: {
                title: string;
                type: any;
                displayStepper: boolean;
                step: number;
                min: number;
                max: number;
                defaultValue: number;
            };
            cPolarAngle: {
                title: string;
                type: any;
                displayStepper: boolean;
                step: number;
                min: number;
                max: number;
                defaultValue: number;
            };
        };
        hidden: (props: any) => boolean;
    };
    position: {
        type: any;
        controls: {
            positionX: {
                type: any;
                step: number;
                displayStepper: boolean;
                defaultValue: number;
            };
            positionY: {
                type: any;
                step: number;
                displayStepper: boolean;
                defaultValue: number;
            };
            positionZ: {
                type: any;
                step: number;
                displayStepper: boolean;
                defaultValue: number;
            };
        };
        hidden: (props: any) => boolean;
    };
    rotation: {
        type: any;
        controls: {
            rotationX: {
                type: any;
                step: number;
                min: number;
                max: number;
                displayStepper: boolean;
                defaultValue: number;
            };
            rotationY: {
                type: any;
                step: number;
                min: number;
                max: number;
                displayStepper: boolean;
                defaultValue: number;
            };
            rotationZ: {
                type: any;
                step: number;
                min: number;
                max: number;
                displayStepper: boolean;
                defaultValue: number;
            };
        };
        hidden: (props: any) => boolean;
    };
    urlString: {
        type: any;
        placeholder: string;
        defaultValue: string;
        hidden: (props: any) => boolean;
    };
    zoomOut: {
        type: any;
        title: string;
        enabledTitle: string;
        disabledTitle: string;
        defaultValue: boolean;
        hidden: (props: any) => boolean;
    };
    toggleAxis: {
        type: any;
        title: string;
        enabledTitle: string;
        disabledTitle: string;
        defaultValue: boolean;
        hidden: (props: any) => boolean;
    };
    enableTransition: {
        type: any;
        title: string;
        enabledTitle: string;
        disabledTitle: string;
        defaultValue: boolean;
        hidden: (props: any) => boolean;
    };
    enableCameraUpdate: {
        type: any;
        title: string;
        enabledTitle: string;
        disabledTitle: string;
        defaultValue: boolean;
        hidden: (props: any) => boolean;
    };
    pointerEvents: {
        type: any;
        title: string;
        options: string[];
        optionTitles: string[];
        displaySegmentedControl: boolean;
        hidden: (props: any) => boolean;
    };
    lazyLoad: {
        type: any;
        defaultValue: boolean;
    };
    threshold: {
        type: any;
        min: number;
        max: number;
        step: number;
        defaultValue: number;
        displayStepper: boolean;
        title: string;
        hidden: (props: any) => boolean;
    };
    rootMargin: {
        type: any;
        placeholder: string;
        defaultValue: string;
        title: string;
        description: string;
        hidden: (props: any) => boolean;
    };
    canvas: {
        type: any;
        title: string;
        controls: {
            pixelDensity: {
                type: any;
                step: number;
                min: number;
                max: number;
                displayStepper: boolean;
                defaultValue: number;
            };
            fov: {
                type: any;
                step: number;
                min: number;
                max: number;
                displayStepper: boolean;
                defaultValue: number;
            };
            preserveDrawingBuffer: {
                type: any;
                title: string;
                defaultValue: boolean;
            };
            powerPreference: {
                type: any;
                title: string;
                options: string[];
                optionTitles: string[];
                displaySegmentedControl: boolean;
                defaultValue: string;
            };
        };
    };
};

declare function formatUrlString(urlString: any): any;
declare function formatFramerProps({ position, rotation, cameraAngle, noise, canvas, ...rest }: {
    [x: string]: any;
    position: any;
    rotation: any;
    cameraAngle: any;
    noise: any;
    canvas: any;
}): {
    positionX: any;
    positionY: any;
    positionZ: any;
    rotationX: any;
    rotationY: any;
    rotationZ: any;
    cAzimuthAngle: any;
    cPolarAngle: any;
    uDensity: any;
    uStrength: any;
    pixelDensity: any;
    fov: any;
    preserveDrawingBuffer: any;
    powerPreference: any;
};

export { type EnvironmentPresetT, type GradientT, type LightTypeT, type LightsT, type MeshT, type Position, type Rotation, ShaderGradient, ShaderGradientCanvas, type ShaderGradientType, type animateT, formatFramerProps, formatUrlString, initialActivePreset, presets, presetsArray, propertyControls, type typeT, useShaderGradientCanvasContext };
